{{- if .Values.caddy.enabled }}
{{- if .Values.caddy.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-caddy
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.caddy.persistence.storageClass }}
  {{- if (eq "-" .Values.caddy.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.caddy.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.caddy.persistence.size | quote }}
{{- end }}
{{- end }}
