apiVersion: v2
name: app
description: Mountain Interactive Laravel Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - laravel
  - php
  - react
  - inertia
maintainers:
  - name: Jon Erickson
